version: "3"

services:
  pgsql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - pgsql
    environment:
      - DATABASE_URL= postgresql://postgres:Databrah91@pgsql:5432/cost_of_living