"""empty message

Revision ID: f032751e19d0
Revises: 
Create Date: 2023-02-05 09:32:04.334911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f032751e19d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisttoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=3), nullable=False),
    sa.Column('usd_to_local_exchange_rate', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city')
    )
    op.create_table('apparel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=70), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('childcare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('annual_price', sa.Float(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('foodbeverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_category', sa.String(length=20), nullable=False),
    sa.Column('purchase_point', sa.String(length=20), nullable=False),
    sa.Column('item', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('homepurchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_location', sa.String(length=30), nullable=False),
    sa.Column('price_per_sqm', sa.Float(), nullable=False),
    sa.Column('mortgage_interest', sa.Float(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('leisure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_location', sa.String(length=30), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('monthly_price', sa.Float(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('transportation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=70), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_table('utilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility', sa.String(length=80), nullable=False),
    sa.Column('monthly_price', sa.Float(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilities')
    op.drop_table('transportation')
    op.drop_table('rent')
    op.drop_table('leisure')
    op.drop_table('homepurchase')
    op.drop_table('foodbeverage')
    op.drop_table('childcare')
    op.drop_table('apparel')
    op.drop_table('location')
    op.drop_table('user')
    op.drop_table('currency')
    op.drop_table('blacklisttoken')
    # ### end Alembic commands ###
