import datetime
import json
import os
import requests_mock
from tests.fixtures.fixtures_testing import mock_boto3_s3, mock_currency_conversion_rates_html, mock_environment_variables
from scripts.extract_currency_conversion_rates import extract_currency_conversion_rates

def test_extract_currency_conversion_rates(requests_mock, mock_boto3_s3, mock_currency_conversion_rates_html, mock_environment_variables):
    # Mock request output
    requests_mock.get('https://www.numbeo.com/common/currency_settings.jsp', text = mock_currency_conversion_rates_html)

    # Expected variables generated by function
    current_date = datetime.date.today().strftime('%Y%m%d')
    expected_object_name = f'currency_conversion_rates{current_date}'
    expected_currency_conversion_rates_json = json.dumps([{"AED": "3.67"}, {"ALL": "99.54"}, {"AMD": "383.76"}, {"AUD": "1.55"}, {"AZN": "1.70"}, {"BAM": "1.83"}, 
    {"BGN": "1.83"}, {"BHD": "0.38"}, {"BRL": "4.86"}, {"BYN": "2.52"}, {"CAD": "1.35"}, {"CHF": "0.90"}, {"CLP": "886.62"}, {"CNY": "7.29"}, {"COP": "3,925.43"}, 
    {"CZK": "22.87"}, {"DKK": "6.98"}, {"EUR": "0.94"}, {"GBP": "0.81"}, {"GEL": "2.64"}, {"HKD": "7.82"}, {"HUF": "358.82"}, {"ILS": "3.82"}, {"ISK": "135.87"}, 
    {"JPY": "147.75"}, {"KRW": "1,323.71"}, {"MDL": "17.92"}, {"MKD": "57.58"}, {"MOP": "8.05"}, {"MXN": "17.13"}, {"MYR": "4.69"}, {"NOK": "10.82"}, {"NZD": "1.69"}, 
    {"OMR": "0.38"}, {"PLN": "4.34"}, {"PYG": "7,258.93"}, {"QAR": "3.64"}, {"RON": "4.65"}, {"RSD": "109.81"}, {"RUB": "96.59"}, {"SAR": "3.75"}, {"SEK": "11.16"}, 
    {"SGD": "1.36"}, {"THB": "35.78"}, {"TRY": "27.01"}, {"TWD": "32.03"}, {"UAH": "36.86"}, {"UYU": "38.07"}])

    # Test function
    extract_currency_conversion_rates()
    mock_boto3_s3.put_object.assert_called_once_with(Bucket = 'bucket', Key = expected_object_name, Body = expected_currency_conversion_rates_json)