import json
import datetime
import pytest
import requests
import requests_mock
from scripts.extract_cities import extract_cities
from tests.fixtures.fixtures_testing import mock_extract_cities_html, mock_countries, mock_environment_variables, mock_boto3_s3

def test_extract_cities(requests_mock, mock_extract_cities_html, mock_countries, mock_environment_variables, mock_boto3_s3):
    # Mock request output
    requests_mock.get('https://www.numbeo.com/cost-of-living/country_result.jsp?country=Australia', text = mock_extract_cities_html)
    
    # Expected variables generated by function
    current_date = datetime.date.today().strftime('%Y%m%d')
    expected_object_name = f'cities{current_date}'
    expected_extracted_cities_json = json.dumps(['Canberra', 'Adelaide', 'Perth', 'Brisbane', 'Sydney', 'Melbourne', 'Newcastle', 'Gold Coast', 'Hobart'])
    
    # Test function
    extract_cities(mock_countries)
    mock_boto3_s3.put_object.assert_called_once_with(Bucket = 'bucket', Key = expected_object_name, Body = expected_extracted_cities_json)