import json
import datetime
import pytest
import requests
import requests_mock
from scripts.extraction import *
from tests.fixtures.fixtures_testing import *

def test_extract_locations_with_cities(requests_mock, mock_locations_with_cities_html, mock_countries_with_cities, mock_environment_variables, mock_boto3_s3, current_date):
    # Mock request output
    requests_mock.get('https://www.numbeo.com/cost-of-living/country_result.jsp?country=Australia', text = mock_locations_with_cities_html)
    
    # Expected variables generated by function
    expected_object_name = f'locations{current_date}'
    expected_extracted_cities_json = json.dumps([{'Country': 'Australia', 'City': 'Canberra'}, {'Country': 'Australia', 'City': 'Adelaide'}, 
    {'Country': 'Australia', 'City': 'Perth'}, {'Country': 'Australia', 'City': 'Brisbane'}, {'Country': 'Australia', 'City': 'Sydney'},
    {'Country': 'Australia', 'City': 'Melbourne'}, {'Country': 'Australia', 'City': 'Newcastle'}, {'Country': 'Australia', 'City': 'Gold Coast'},
    {'Country': 'Australia', 'City': 'Hobart'}])
    
    # Test function
    extract_locations(mock_countries_with_cities)
    mock_boto3_s3.put_object.assert_called_once_with(Bucket = 'test-bucket-raw', Key = expected_object_name, Body = expected_extracted_cities_json)

def test_extract_locations_without_cities(requests_mock, mock_locations_without_cities_html, mock_countries_without_cities, mock_environment_variables, mock_boto3_s3, current_date):
    # Mock request output
    requests_mock.get('https://www.numbeo.com/cost-of-living/country_result.jsp?country=Hong%20Kong', text = mock_locations_without_cities_html)
    
    # Expected variables generated by function
    expected_object_name = f'locations{current_date}'
    expected_extracted_cities_json = json.dumps([{'Country': 'Hong Kong', 'City': None}])
    
    # Test function
    extract_locations(mock_countries_without_cities)
    mock_boto3_s3.put_object.assert_called_once_with(Bucket = 'test-bucket-raw', Key = expected_object_name, Body = expected_extracted_cities_json)

def test_extract_currency_conversion_rates(requests_mock, mock_boto3_s3, mock_currency_conversion_rates_html, mock_environment_variables, current_date):
    # Mock request output
    requests_mock.get('https://www.numbeo.com/common/currency_settings.jsp', text = mock_currency_conversion_rates_html)

    # Expected variables generated by function
    expected_object_name = f'currency_conversion_rates{current_date}'
    expected_currency_conversion_rates_json = json.dumps([{"Abbreviation": "AED", "USD_to_local": "3.67"}, {"Abbreviation": "AUD", "USD_to_local": "1.55"}, 
    {"Abbreviation": "BAM", "USD_to_local": "1.83"}, {"Abbreviation": "BGN", "USD_to_local": "1.83"}, {"Abbreviation": "BHD", "USD_to_local": "0.38"},
    {"Abbreviation": "BRL", "USD_to_local": "4.86"}, {"Abbreviation": "CAD", "USD_to_local": "1.35"}, {"Abbreviation": "CHF", "USD_to_local": "0.90"}, 
    {"Abbreviation": "CLP", "USD_to_local": "886.62"}, {"Abbreviation": "CNY", "USD_to_local": "7.29"}, {"Abbreviation": "COP", "USD_to_local": "3,925.43"}, 
    {"Abbreviation": "CRC", "USD_to_local": "529.05"}, {"Abbreviation": "CZK", "USD_to_local": "22.87"}, {"Abbreviation": "DKK", "USD_to_local": "6.98"}, 
    {"Abbreviation": "EUR", "USD_to_local": "0.94"}, {"Abbreviation": "GBP", "USD_to_local": "0.81"}, {"Abbreviation": "GEL", "USD_to_local": "2.64"}, 
    {"Abbreviation": "HKD", "USD_to_local": "7.82"}, {"Abbreviation": "HUF", "USD_to_local": "358.82"}, {"Abbreviation": "ILS", "USD_to_local": "3.82"}, 
    {"Abbreviation": "ISK", "USD_to_local": "135.87"}, {"Abbreviation": "JPY", "USD_to_local": "147.75"}, {"Abbreviation": "KRW", "USD_to_local": "1,323.71"}, 
    {"Abbreviation": "KWD", "USD_to_local": "0.31"}, {"Abbreviation": "MOP", "USD_to_local": "8.05"}, {"Abbreviation": "MXN", "USD_to_local": "17.13"}, 
    {"Abbreviation": "MYR", "USD_to_local": "4.69"}, {"Abbreviation": "NOK", "USD_to_local": "10.82"}, {"Abbreviation": "NZD", "USD_to_local": "1.69"}, 
    {"Abbreviation": "OMR", "USD_to_local": "0.38"}, {"Abbreviation": "PLN", "USD_to_local": "4.34"}, {"Abbreviation": "PYG", "USD_to_local": "7,258.93"}, 
    {"Abbreviation": "QAR", "USD_to_local": "3.64"}, {"Abbreviation": "RON", "USD_to_local": "4.65"}, {"Abbreviation": "RSD", "USD_to_local": "109.81"}, 
    {"Abbreviation": "RUB", "USD_to_local": "96.59"}, {"Abbreviation": "SAR", "USD_to_local": "3.75"}, {"Abbreviation": "SEK", "USD_to_local": "11.16"}, 
    {"Abbreviation": "SGD", "USD_to_local": "1.36"}, {"Abbreviation": "THB", "USD_to_local": "35.78"}, {"Abbreviation": "TRY", "USD_to_local": "27.01"}, 
    {"Abbreviation": "TWD", "USD_to_local": "32.03"}, {"Abbreviation": "UAH", "USD_to_local": "36.86"}, {"Abbreviation": "UYU", "USD_to_local": "38.07"}])

    # Test function
    extract_currency_conversion_rates()
    mock_boto3_s3.put_object.assert_called_once_with(Bucket = 'test-bucket-raw', Key = expected_object_name, Body = expected_currency_conversion_rates_json)

def test_extract_livingcost_prices_from_city(requests_mock, mock_environment_variables, mock_boto3_s3, mock_livingcost_prices_perth_html, current_date):
    # Mock request output
    requests_mock.get('https://livingcost.org/cost/australia/perth', text = mock_livingcost_prices_perth_html)

    # Expected variables generated by function
    expected_object_name = f'livingcost_price_info{current_date}'
    expected_livingcost_price_info_json = json.dumps([{'City': 'Perth', 'Item': 'Lunch', 'Price': '$15.4'},
        {'City': 'Perth', 'Item': 'Coke (0.5L)', 'Price': '$2.95'},
        {'City': 'Perth', 'Item': 'Electricity, Heating, Cooling, Water and Garbage (1 Person)', 'Price': '$124' },
        {'City': 'Perth', 'Item': 'Electricity, Heating, Cooling, Water and Garbage (Family)', 'Price': '$216'},
        {'City': 'Perth', 'Item': 'Taxi (8km)', 'Price': '$17.4'},
        {'City': 'Perth', 'Item': 'Water (1L)', 'Price': '$1.43'},
        {'City': 'Perth', 'Item': 'Wine (750ml Bottle Mid Range)', 'Price': '$13.4'},
        {'City': 'Perth', 'Item': 'Brand Sneakers', 'Price': '$139'}])

    # Test function
    extract_livingcost_prices_from_city()
    mock_boto3_s3.get_object.assert_called_once_with(Bucket = 'test-bucket-raw', Key = f'cities{current_date}')
    mock_boto3_s3.put_object.assert_called_once_with(Bucket = 'test-bucket-raw', Key = expected_object_name, Body = expected_livingcost_price_info_json)

def test_extract_numbeo_prices_from_city(requests_mock, mock_environment_variables, mock_boto3_s3, mock_numbeo_prices_perth_html, current_date):
    # Mock request output
    requests_mock.get('https://www.numbeo.com/cost-of-living/in/Perth?displayCurrency=USD', text = mock_numbeo_prices_perth_html)

    # Expected variables generated by function
    expected_object_name = f'numbeo_price_info{current_date}'
    expected_numbeo_price_info_json = json.dumps([{"City": "Perth", "Item": "Dinner (2 People Mid Range Restaurant)", "Price": "96.31\u00a0$"},
    {"City": "Perth", "Item": "Domestic Draught (0.5L)", "Price": "7.41\u00a0$"},
    {"City": "Perth", "Item": "Cappuccino (Regular)", "Price": "3.64\u00a0$"},
    {"City": "Perth", "Item": "Milk (1L)", "Price": "1.82\u00a0$"},
    {"City": "Perth", "Item": "Bread (500g)", "Price": "2.44\u00a0$"},
    {"City": "Perth", "Item": "Rice (1kg)", "Price": "2.19\u00a0$"},
    {"City": "Perth", "Item": "Eggs (x12)", "Price": "4.22\u00a0$"},
    {"City": "Perth", "Item": "Cheese (1kg)", "Price": "9.47\u00a0$"},
    {"City": "Perth", "Item": "Chicken Fillets (1kg)", "Price": "8.85\u00a0$"},
    {"City": "Perth", "Item": "Beef Round (1kg)", "Price": "14.47\u00a0$"},
    {"City": "Perth", "Item": "Apples (1kg)", "Price": "3.44\u00a0$"},
    {"City": "Perth", "Item": "Banana (1kg)", "Price": "2.58\u00a0$"},
    {"City": "Perth", "Item": "Oranges (1kg)", "Price": "2.93\u00a0$"},
    {"City": "Perth", "Item": "Tomato (1kg)", "Price": "4.27\u00a0$"},
    {"City": "Perth", "Item": "Potato (1kg)", "Price": "2.19\u00a0$"},
    {"City": "Perth", "Item": "Onion (1kg)", "Price": "1.76\u00a0$"},
    {"City": "Perth", "Item": "Lettuce (1 Head)", "Price": "2.27\u00a0$"},
    {"City": "Perth", "Item": "Domestic Beer (0.5L Bottle)", "Price": "4.62\u00a0$"},
    {"City": "Perth", "Item": "Cigarettes (20 Pack Malboro)", "Price": "26.41\u00a0$"},
    {"City": "Perth", "Item": "Public Transport (One Way Ticket)", "Price": "2.90\u00a0$"},
    {"City": "Perth", "Item": "Public Transport (Monthly)", "Price": "112.90\u00a0$"},
    {"City": "Perth", "Item": "Petrol (1L)", "Price": "1.26\u00a0$"},
    {"City": "Perth", "Item": "Mobile Plan (10GB+ Data, Monthly)", "Price": "35.83\u00a0$"},
    {"City": "Perth", "Item": "Internet (60 Mbps, Unlimited Data, Monthly)", "Price": "62.23\u00a0$"},
    {"City": "Perth", "Item": "Gym Membership (Monthly)", "Price": "49.05\u00a0$"},
    {"City": "Perth", "Item": "Tennis Court Rent (1hr)", "Price": "14.92\u00a0$"},
    {"City": "Perth", "Item": "Cinema International Release", "Price": "14.82\u00a0$"},
    {"City": "Perth", "Item": "Daycare / Preschool (1 Month)", "Price": "1,617.64\u00a0$"},
    {"City": "Perth", "Item": "International Primary School (1 Year)", "Price": "13,498.21\u00a0$"},
    {"City": "Perth", "Item": "Pair of Jeans", "Price": "87.19\u00a0$"},
    {"City": "Perth", "Item": "Summer Dress Chain Store", "Price": "62.76\u00a0$"},
    {"City": "Perth", "Item": "Mens Leather Business Shoes", "Price": "161.79\u00a0$"},
    {"City": "Perth", "Item": "Rent 1 Bedroom Apartment City Centre", "Price": "1,635.10\u00a0$"},
    {"City": "Perth", "Item": "Rent 1 Bedroom Apartment Outside City Centre", "Price": "1,191.26\u00a0$"},
    {"City": "Perth", "Item": "Rent 3 Bedroom Apartment City Centre", "Price": "2,454.62\u00a0$"},
    {"City": "Perth", "Item": "Rent 3 Bedroom Apartment Outside City Centre", "Price": "1,763.16\u00a0$"},
    {"City": "Perth", "Item": "Price per Square Meter to Buy Apartment in City Centre", "Price": "6,741.52\u00a0$"},
    {"City": "Perth", "Item": "Price per Square Meter to Buy Apartment Outside of Centre", "Price": "5,395.77\u00a0$"}])

    # Test function
    extract_numbeo_prices_from_city()
    mock_boto3_s3.get_object.assert_called_once_with(Bucket = 'test-bucket-raw', Key = f'cities{current_date}')
    mock_boto3_s3.put_object.assert_called_once_with(Bucket = 'test-bucket-raw', Key = expected_object_name, Body = expected_numbeo_price_info_json)